steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yarrabotula/CI-CD-Pipeline.git']
  
  #Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/brilliant-scene-290913/hello123:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/brilliant-scene-290913/hello123:latest']
  
# deploy container image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/nginx-1'
  - 'nginx-1=gcr.io/brilliant-scene-290913/hello123:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetesproject'
  
  substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: My First Project
    _ZONE: europe-west2-a
    _GKE_CLUSTER: kubernetesproject
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: nginx-1
    _CONTAINERNAME:  nginx-1
    _REPO_NAME: CI-CD-Pipeline
    
    # Developers ONLY change
    _VERSION: v1.0
    
    options:
    substitution_option: 'ALLOW_LOOSE'
    
    
