steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/brilliant-scene-290913/git'
  args: ['clone','https://github.com/yarrabotula/CI-CD-Pipeline.git']

#Build the image 
- name: 'gcr.io/brilliant-scene-290913/hello123'
  args: ['build','-t','gcr.io/brilliant-scene-290913/hello123:latest','.']

#Push the image  
- name: 'gcr.io/brilliant-scene-290913/hello123'
  args: ['push','gcr.io/brilliant-scene-290913/hello123:latest']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/venkat1234'
  - 'hello123=gcr.io/brilliant-scene-290913/hello123:v1'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetesproject'
  

    _VERSION: v1.0
    

