steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yarrabotula/CI-CD-Pipeline.git']

steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/brilliant-scene-290913/hello123:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/brilliant-scene-290913/hello123:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --image=gcr.io/brilliant-scene-290913/hello123:latest
  - --location=us-central1-c
  - --cluster=hello
