steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/yarrabotula/CI-CD-Pipeline.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/brilliant-scene-290913/hello123:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/brilliant-scene-290913/hello123']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/venkat1234'
  - 'hello123=gcr.io/brilliant-scene-290913/hello123:v1'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: learn-gcp-with-mahesh
    _ZONE: asia-south1-a
    _GKE_CLUSTER: learn-gcp-with-mahesh-gke-cluster
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-world-service
    _CONTAINERNAME: hello-world-service    
    _REPO_NAME: cicd-service
    
    # Developers ONLY change
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'
