apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello123
  template:
    metadata:
      labels:
        app: hello123
    spec:
      containers:
      - name: hello-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/brilliant-scene-290913/hello123:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
